//---------------------------------------------------------------
//<auto-generated>
//      This code was generated by ResxTranslator.
//      **** Do NOT edit this file!!! ****
//      Any changes to this file will be lost upon regeneration.
//</auto-generated>
//---------------------------------------------------------------
using System.Windows.Forms;
using static System.Windows.Forms.ListView;

namespace LanguageResourceManager
{
    using System;  
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class LangRes<T>
    {

            private static global::System.Resources.ResourceManager resourceMan;

            private static global::System.Globalization.CultureInfo resourceCulture;

            [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]

            /// <summary>
            ///   Returns the cached ResourceManager instance used by this class.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Resources.ResourceManager ResourceManager
            {
                get
                {
                    if (object.ReferenceEquals(resourceMan, null))
                    {
                        string TypeString = typeof(T).ToString();
                    // global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager(TypeString, typeof(T).Assembly);
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TranslateFileNamesForm.Form1", typeof(TranslateFileNamesForm.Form1).Assembly);
                    resourceMan = temp;
                    }
                    return resourceMan;
                }
            }

            /// <summary>
            ///   Overrides the current thread's CurrentUICulture property for all
            ///   resource lookups using this strongly typed resource class.
            /// </summary>
            [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
            public static global::System.Globalization.CultureInfo Culture
            {
                get
                {
                    return resourceCulture;
                }
                set
                {
                    resourceCulture = value;
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to FooFoo.
            /// </summary>
            public static string Foofoo
            {
                get
                {
                    return ResourceManager.GetString("Foofoo", resourceCulture);
                }
            }

            /// <summary>
            ///   Looks up a localized string similar to Rename All.
            /// </summary>
            public static string RenameAll
            {
                get
                {
                    return ResourceManager.GetString("RenameAll", resourceCulture);
                }
            }


    }
}
